### ISSUE TITLE
Scheduler: can't delete/create job because client seems to be 'str'

### ISSUE THREAD

**Issue by davidedironza** [googleapis/python-scheduler#12]
Hello

When I try to create or delete a job the client don't recognize the mode create, delete, ....

#### Environment details
1. Scheduler
2. Windows 10
3. Python version and virtual environment information: Python 3.7.3
4. google-cloud-scheduler-1.2.1

#### Code example

```
from google.cloud import scheduler_v1
import logging

client = scheduler_v1.CloudSchedulerClient()
name = client.job_path(GCP_PROJECT, "europe-west6", "test")
client.delete_job(name)
```

#### Stack trace
```
Traceback (most recent call last):
  File "C:\Users\C203580\.conda\envs\gcp_onboarding\lib\site-packages\IPython\core\interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-28-26eba677eb8b>", line 1, in <module>
    client.delete_job(name)
  File "C:\Users\C203580\.conda\envs\gcp_onboarding\lib\site-packages\google\cloud\scheduler_v1\gapic\cloud_scheduler_client.py", line 621, in delete_job
    self.transport.delete_job,
AttributeError: 'str' object has no attribute 'delete_job'

```

Cheers
Davide

**Comment by busunkim96** [comment]
Hi @davidedironza,

I'm unable to reproduce this in a clean virtual environment. 
```sh
python3 -m venv env
source env/bin/activate
python3 -m pip install google-cloud-scheduler
```

Could you do a `pip freeze` so we can see your other dependencies?

**Comment by davidedironza** [comment]
Hi @busunkim96 

Here the output of pip freeze

`alabaster==0.7.12
appdirs==1.4.3
argh==0.26.2
asn1crypto==1.3.0
astroid==2.3.3
atomicwrites==1.3.0
attrs==19.3.0
autopep8==1.4.4
Babel==2.8.0
backcall==0.1.0
bcrypt==3.1.7
bleach==3.1.0
cached-property==1.5.1
cachetools==4.0.0
CCDA-Standard-Functions==2020.1.20
certifi==2019.11.28
cffi==1.13.2
chardet==3.0.4
cloudpickle==1.2.2
colorama==0.4.3
convertdate==2.2.0
cryptography==2.8
cx-Oracle==7.3.0
DAP-Standard-Functions==2020.2.10
decorator==4.4.1
defusedxml==0.6.0
diff-match-patch==20181111
docutils==0.16
entrypoints==0.3
flake8==3.7.9
future==0.18.2
google-api-core==1.16.0
google-auth==1.11.0
google-auth-oauthlib==0.4.1
google-cloud-bigquery==1.24.0
google-cloud-core==1.3.0
google-cloud-kms==1.2.1
google-cloud-logging==1.14.0
google-cloud-monitoring==0.34.0
google-cloud-pubsub==1.2.0
google-cloud-scheduler==1.2.1
google-cloud-storage==1.25.0
google-resumable-media==0.5.0
googleapis-common-protos==1.51.0
grpc-google-iam-v1==0.12.3
grpcio==1.27.1
hdbcli==2.4.182
holidays==0.10.1
idna==2.8
imagesize==1.2.0
importlib-metadata==1.5.0
inflect==4.1.0
intervaltree==3.0.2
ipykernel==5.1.4
ipython==7.12.0
ipython-genutils==0.2.0
isodate==0.6.0
isort==4.3.21
jaraco.itertools==5.0.0
jedi==0.14.1
Jinja2==2.11.1
jsonschema==3.2.0
jupyter-client==5.3.4
jupyter-core==4.6.1
keyring==21.1.0
lazy-object-proxy==1.4.3
ldap3==2.6.1
libkeepass==0.3.1.post1
lxml==4.5.0
MarkupSafe==1.1.1
mccabe==0.6.1
mistune==0.8.4
mkl-fft==1.0.15
mkl-random==1.1.0
mkl-service==2.3.0
more-itertools==8.2.0
nbconvert==5.6.1
nbformat==5.0.4
numpy==1.18.1
numpydoc==0.9.2
oauthlib==3.1.0
packaging==20.1
pandas==1.0.0
pandas-gbq==0.13.0
pandocfilters==1.4.2
paramiko==2.6.0
parso==0.6.0
pathtools==0.1.2
pexpect==4.8.0
pickleshare==0.7.5
pluggy==0.13.1
prompt-toolkit==3.0.3
protobuf==3.11.3
psutil==5.6.7
pyarrow==0.16.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycodestyle==2.5.0
pycparser==2.19
pycryptodome==3.9.7
pydata-google-auth==0.3.0
pydocstyle==4.0.1
pyflakes==2.1.1
Pygments==2.5.2
pylint==2.4.4
PyMeeus==0.3.7
pymongo==3.10.1
PyNaCl==1.3.0
pyodbc==4.0.30
pyOpenSSL==19.1.0
pyparsing==2.4.6
pyrsistent==0.15.7
PySocks==1.7.1
python-dateutil==2.8.1
python-jsonrpc-server==0.3.4
python-language-server==0.31.7
pytz==2019.3
pywin32==227
pywin32-ctypes==0.2.0
PyYAML==5.3
pyzmq==18.1.1
QDarkStyle==2.8
QtAwesome==0.6.1
qtconsole==4.6.0
QtPy==1.9.0
requests==2.22.0
requests-oauthlib==1.3.0
requests-toolbelt==0.9.1
rope==0.16.0
rsa==4.0
Rtree==0.9.3
six==1.14.0
snowballstemmer==2.0.0
sortedcontainers==2.1.0
Sphinx==2.3.1
sphinxcontrib-applehelp==1.0.1
sphinxcontrib-devhelp==1.0.1
sphinxcontrib-htmlhelp==1.0.2
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.2
sphinxcontrib-serializinghtml==1.1.3
spyder==4.0.1
spyder-kernels==1.8.1
SQLAlchemy==1.3.13
testpath==0.4.4
tornado==6.0.3
traitlets==4.3.3
ujson==1.35
urllib3==1.25.8
watchdog==0.10.1
wcwidth==0.1.8
webencodings==0.5.1
win-inet-pton==1.1.0
wincertstore==0.2
wrapt==1.11.2
yapf==0.28.0
zeep==3.4.0
zipp==2.1.0`

**Comment by davidedironza** [comment]
It seems that I solved this issue by myselfe.
In my code I hade 
client = scheduler_v1.CloudSchedulerClient(**GCP_PROJECT**)
withoud **GCP_PROJECT** it works
