### ISSUE TITLE
Example showing Job with Cloud PubSub Target

### ISSUE THREAD

**Issue by Arc-Jung** [googleapis/python-scheduler#151]
**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

I will create schedulable Serverless Application. And my Serverless Application use Cloud Pub/Sub with Cloud Schedule in GCP.

At this time, I want make Cloud Schedule Job with Python SDK. So that I finded SDK document.

> https://googleapis.dev/python/cloudscheduler/latest/scheduler_v1/types.html#google.cloud.scheduler_v1.types.CreateJobRequest 

> https://github.com/googleapis/python-scheduler/blob/main/samples/snippets/create_job.py

But i don't know this SDK use case with Cloud PubSub. Please show me  Cloud Pub/Sub trigger example.

Best Regards

**Comment by parthea** [comment]
I'm going to close this issue as a response was provided but please feel free to re-open it.
